version: 2

jobs:
  build:
    working_directory: /go/src/github.com/wearefair/okta-auth
    docker:
      - image: golang:1.11
    steps:
      - checkout
      - run:
          name: Install dep tool
          command: |
            go get -u github.com/golang/dep/cmd/dep
      - run:
          name: Install dependencies
          command: |
            dep ensure
      - run:
          name: Run unit tests
          command: |
            go test -race -v ./...
